### ISSUE TITLE
Css and download not working 

### ISSUE THREAD

**Issue by Sarfroz** [Strikesoft/Downloader#8]
Hi sir i installed it via composer but its not working click on download has not effect and Css also not working
http://i.imgur.com/tyJVO8v.png

**Comment by Johann-S** [comment]
Hi first of all thank you for using Downloader,

Is it possible for you to show me the URL you used ? 

You have to rename this file : https://github.com/Strikesoft/Downloader/blob/master/config/param.yml.dist to **param.yml**

and you have to setup your apache like this : 
```
<VirtualHost yourURL>
    ServerName yourURL
    DocumentRoot /var/www/Downloader/web/
    <Directory /var/www/Downloader/web/>
        AllowOverride All
        Order Allow,Deny
        Allow from All
    </Directory>
    ErrorLog "logs/downloader-error.log"
</VirtualHost>
```
X-Ref : #9

**Comment by Sarfroz** [comment]
sir i am using nginx. will tere be any issue. also does mega.co.nz support
resume downloads.

**Comment by Johann-S** [comment]
Mega.co.nz support will arrive soon see : https://github.com/Strikesoft/Downloader/issues/2

About nginx I'm not an expert but can you try this configuration : 
```
 server {
        listen   80;
        root /var/www/Downloader/web/;
        index index.php;
        server_name yourURL;
}

**Comment by Sarfroz** [comment]
then i have to wait sir. kindly make resume support streaming downloads

**Comment by Johann-S** [comment]
Yes sorry Downloader isn't finished yet.

Can you tell me if Nginx setup worked and if you can use Downloader ? thank you

**Comment by Sarfroz** [comment]
finaly working sir. Thanks hope you will ad mega.co soon with resume
support.
http://web.hbl.bz/

**Comment by Johann-S** [comment]
Sure I'll work on it 👍

**Comment by Sarfroz** [comment]
sir one more thing i created downloader with the help of
https://github.com/MrSwiss/mega-downloader/blob/master/mega.class.php
but the problem is no resume . Though there are some service who give resume with streaming downloads. If you able to make i will donate for that script since  i really need it.

here is my server example link:
 http://mega.co.nz/#!nk4XCZBY!8z8sfyU8ICrffclUgxbrVYyq7gHjNcRoaWfCwPPMLaU

my server link:
http://51.15.39.248/mega/aqep9mesz2eg/mmkz-004.rar   (no resume)

service which give resume with same link:

http://dl-srv74.zevera.com/Download/directDownload.ashx?qs=t%2b3g%2fr2vw%2fXojZCfPZgC3Bd23v0gIZzI3hI5kS09Ivz0ZLFX%2fZE9U9DGu%2fR0tdFYLBZImPIs2jdUUMMM11fbf7pIv0OnP0Yo3o9twhkvyW6TkeCLodH0DyMoXMqmZIvK9JAssUvJbcqHP1vpVMM5goDHo6cH94Q6JtcrkHTs%2bLZSvMd2%2b7BK4opb9bmuYgtoAEmNuOg5kHfDYuUcegAr1LPzB9G09gWf


i hope you will surely find the solution, since till now no one able to give the solution for this on github
